database:
  dialect: mysql+pymysql
  url: localhost
  port: 3306
  name: aristotle
  userName: root
  password: root

locale: en_EN

request:
  timeout: 3
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11

parser:
  metaTitle: ["title", "og:title", "twitter:title"]
  metaDescription: ["description", "og:description", "twitter:description"]
  metaImage: ["og:image", "og:image:url", "twitter:image"]
  metaPublishDate: ["datePublished", "og:article:published_time", "article:published_time"]
  titleCharLimit: 100
  descriptionCharLimit: 300