article:
  - domain: bbc.com
    active: true
    link: https://www.bbc.com
    filterForLink:
      mandatoryWords: [".html"]
      permissibleWords: ['-']
      impermissibleWords: []
    tagForMetadata:
      title:
      description:
      image:
      publishDate: span,class,date-item added
      publishDateFormat: "%d.%m.%Y"

  - domain: theguardian.com
    active: true
    link: https://www.theguardian.com/international
    filterForLink:
      mandatoryWords: ["."]
      permissibleWords: ['-']
      impermissibleWords: []
    tagForMetadata:
      title:
      description:
      image:
      publishDate: dateTime
      publishDateFormat: "%d.%m.%Y"

technology:
  - domain: mashable.com
    active: true
    link: https://mashable.com
    filterForLink:
      mandatoryWords: ["-"]
      permissibleWords: ['/article/']
      impermissibleWords: []
    tagForMetadata:
      title:
      description:
      image:
      publishDate: datetime
      publishDateFormat: "%d.%m.%Y"

  - domain: test.com
    active: true
    link: https://test.com
    filterForLink:
      mandatoryWords: ["-"]
      permissibleWords: ['/article/']
      impermissibleWords: []
    tagForMetadata:
      title:
      description:
      image:
      publishDate: date
      publishDateFormat: "%d.%m.%Y"