gundem:
  - domain: sozcu.com.tr
    active: true
    link: https://www.sozcu.com.tr
    filterForLink:
      mandatoryWords: ["-"]
      permissibleWords: ['/gundem/', '/gunun-icinden/', '/dunya/', '/ekonomi/', '/egitim/', '/saglik/']
      impermissibleWords: ['spor_', 'video.', '/yazarlar/', '/kategori/']
    tagForMetadata:
      title:
      description:
      image:
      publishDate: time,datetime
      publishDateFormat: "%Y-%m-%d"

  - domain: t24.com.tr
    active: true
    link: https://t24.com.tr
    filterForLink:
      mandatoryWords: [","]
      permissibleWords: ['/haber/',]
      impermissibleWords: []
    tagForMetadata:
      title:
      description:
      image:
      publishDate: div,class,_392lz
      publishDateFormat: "%d %B %Y"


teknoloji:
  - domain: chip.com.tr
    active: true
    link: https://www.chip.com.tr
    filterForLink:
      mandatoryWords: [".html"]
      permissibleWords: ['/haber/', '/makale/', '/blog/', '/inceleme/']
      impermissibleWords: []
    tagForMetadata:
      title:
      description:
      image:
      publishDate: time,content
      publishDateFormat: "%Y-%m-%d"

  - domain: webrazzi.com
    active: true
    link: https://webrazzi.com
    filterForLink:
      mandatoryWords: []
      permissibleWords: ['-',]
      impermissibleWords: []
    tagForMetadata:
      title:
      description:
      image:
      publishDate: span,class,sp-date
      publishDateFormat: "%d %B %Y"