article:
  - domain: haber7.com
    active: true
    link: https://www.haber7.com
    filterForLink:
      permissibleWords: ['-']
      impermissibleWords: []
    tagForMetadata:
      title: og:title
      description: og:description
      image: og:image
      publishDate: span,class,date-item added
      publishDateFormat: "%d.%m.%Y"

  - domain: haberturk.com
    active: true
    link: https://www.haberturk.com
    filterForLink:
      permissibleWords: ['-']
      impermissibleWords: []
    tagForMetadata:
      title: og:title
      description: og:description
      image: og:image
      publishDate: dateTime
      publishDateFormat: "%d.%m.%Y"

video-news:
  - domain: test.com
    active: true
    link: https://test.com
    filterForLink:
      permissibleWords: ['/article/']
      impermissibleWords: []
    tagForMetadata:
      title: og:title
      description: og:description
      image: og:image
      publishDate: date
      publishDateFormat: "%d.%m.%Y"

  - domain: test.com
    active: true
    link: https://test.com
    filterForLink:
      permissibleWords: ['/article/']
      impermissibleWords: []
    tagForMetadata:
      title: og:title
      description: og:description
      image: og:image
      publishDate: date
      publishDateFormat: "%d.%m.%Y"

technology:
  - domain: mashable.com
    active: true
    link: https://mashable.com
    filterForLink:
      permissibleWords: ['/article/']
      impermissibleWords: []
    tagForMetadata:
      title: og:title
      description: og:description
      image: og:image
      publishDate: datetime
      publishDateFormat: "%d.%m.%Y"

  - domain: test.com
    active: true
    link: https://test.com
    filterForLink:
      permissibleWords: ['/article/']
      impermissibleWords: []
    tagForMetadata:
      title: og:title
      description: og:description
      image: og:image
      publishDate: date
      publishDateFormat: "%d.%m.%Y"