article:
  - domain: haberturk.com
    link: https://www.haberturk.com
    filterForLink:
      permissibleWords: ['-']
      impermissibleWords: []
    tagForMetadata:
      title: og:title
      description: og:description
      image: og:image
      publishDate: data-datetime

  - domain: test.com
    link: https://test.com
    filterForLink:
      permissibleWords: ['/article/']
      impermissibleWords: []
    tagForMetadata:
      title: og:title
      description: og:description
      image: og:image
      publishDate: date

video-news:
  - domain: test.com
    link: https://test.com
    filterForLink:
      permissibleWords: ['/article/']
      impermissibleWords: []
    tagForMetadata:
      title: og:title
      description: og:description
      image: og:image
      publishDate: date

  - domain: test.com
    link: https://test.com
    filterForLink:
      permissibleWords: ['/article/']
      impermissibleWords: []
    tagForMetadata:
      title: og:title
      description: og:description
      image: og:image
      publishDate: date

technology:
  - domain: mashable.com
    link: https://mashable.com
    filterForLink:
      permissibleWords: ['/article/']
      impermissibleWords: []
    tagForMetadata:
      title: og:title
      description: og:description
      image: og:image
      publishDate: datetime

  - domain: test.com
    link: https://test.com
    filterForLink:
      permissibleWords: ['/article/']
      impermissibleWords: []
    tagForMetadata:
      title: og:title
      description: og:description
      image: og:image
      publishDate: date