database:
  url: localhost
  name: aristotle
  userName: root
  password: root

userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11
siteLocalPath: '/var/www/html/'

# Filter links
blackListWords: ['javascript:', ]

# Link Metadata
titleKeys: ['og:title']
descriptionKeys: ['description', 'og:description']
imageLinkKeys: ['og:image']
publishDateKeys: ['datePublished', 'og:article:published_time']